FROM centos:7

ADD ./haproxy-1.6.14-1.el7.x86_64.rpm /opt/haproxy-1.6.14-1.el7.x86_64.rpm

RUN yum install -y epel-release --releasever=7 && \

    yum install -y  --releasever=7 software-properties-common git libnl3-cli libnl3 mercurial supervisor \

    && cd /opt && yum install -y  --releasever=7 haproxy-1.6.14-1.el7.x86_64.rpm \

    && rm -rf /var/cache/yum/x86_64 /opt/haproxy-1.8.12-1.el7.centos.x86_64.rpm

RUN yum install -y  --releasever=7  rsyslog
